services:
  - type: web
    name: hellobluegk-demo
    env: docker
    dockerfilePath: Dockerfile.render
    dockerContext: .
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:$PORT
    healthCheckPath: /Health
